# Numpyを使おう

In [1]:
import numpy as np

In [2]:
data1 = np.array([1, 2, 3])
data1

array([1, 2, 3])

In [3]:
# ベクトルdata1の型は numpy.ndarray
type(data1)

numpy.ndarray

In [4]:
#ベクトルdata1の要素の型はdtypeで調べられる
data1.dtype

dtype('int64')

In [5]:
# 明示的に型を指定
data6 = np.array([1, 2, 3], dtype=float)
data6.dtype

dtype('float64')

In [6]:
data2 = np.array([[1, 2, 3], [4, 5, 6]])
data2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# 次元数（次元の軸の数、ベクトル→1、行列→2）
data2.ndim

2

In [8]:
data2.shape

(2, 3)

In [10]:
# shapeはreshapeで変更可能（行列→ベクトル）
data2_reshape_6 = data2.reshape(6)
data2_reshape_6

array([1, 2, 3, 4, 5, 6])

In [12]:
# shapeはreshapeで変更可能（行列→行列）
data2_reshape_32 = data2.reshape((3, 2))
data2_reshape_32

array([[1, 2],
       [3, 4],
       [5, 6]])

|  主なプロパティ |  値  |
| ---- | ---- |
|  T  |  転置  |
|  itemsize  |  1要素のサイズ  |
|  nbytes  |  多次元配列全体のサイズ  |

In [13]:
data2

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
# 転置（行と列を入れ替えた多次元配列）
data2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [15]:
# リストから3次元配列作成
data3 = np.array([[[1, 2, 3], [4, 5, 6]], [[11, 12, 13], [14, 15, 16]]])
data3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [16]:
# 3次元配列の転置
#  0軸と2軸を入れ替え
data3.T

array([[[ 1, 11],
        [ 4, 14]],

       [[ 2, 12],
        [ 5, 15]],

       [[ 3, 13],
        [ 6, 16]]])

In [17]:
# 各次元のサイズのタプル
data3.shape

(2, 2, 3)

In [18]:
# 各次元のサイズのタプル
data3.T.shape

(3, 2, 2)

In [19]:
# 1要素のサイズ（バイト）
data2.itemsize

8

In [20]:
# 配列全体のサイズ（バイト）
data2.nbytes

48

In [24]:
# data2.nbytes と data2.itemsize * data2.size は等しい
data2.itemsize * data2.size

48

- Numpyのデータ構造の基本（多次元配列の生成）

In [27]:
# 要素が全て０の一次元配列
np_zeros_3 = np.zeros(3)
np_zeros_3

array([ 0.,  0.,  0.])

In [29]:
# 要素が全て0の２次元配列
np_zeros_23 = np.zeros((2,3))
np_zeros_23

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [31]:
#要素が全て1の１次元配列
np_ones_3 = np.ones(3)
np_ones_3

array([ 1.,  1.,  1.])

In [32]:
#要素が全て1の２次元配列
np_ones_23 = np.ones((2,3))
np_ones_23

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [34]:
#要素が全て5の１次元配列
np_full5_1 = np.full(3, 5)
np_full5_1

array([5, 5, 5])

In [35]:
np_full5_23 = np.full((2,3), 5)
np_full5_23

array([[5, 5, 5],
       [5, 5, 5]])

- shapeが同じ多次元配列からの作成方法

In [37]:
# 全て0に置き換えた新しい多次元配列
np_zeros_like_23 = np.zeros_like(np_ones_23)
np_zeros_like_23

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [38]:
# 全て1に置き換えた新しい多次元配列
np_ones_like_23 = np.ones_like(np_zeros_23)
np_ones_like_23

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [39]:
# 全て5に置き換えた新しい多次元配列
np_full_like_23_5 = np.full_like(np_zeros_23, 5)
np_full_like_23_5

array([[ 5.,  5.,  5.],
       [ 5.,  5.,  5.]])

In [40]:
# 型を指定することもできます
np_full_like_23_5int = np.full_like(np_zeros_23, 5, dtype=int)
np_full_like_23_5int

array([[5, 5, 5],
       [5, 5, 5]])

- 主な生成関数

In [42]:
# rangeのNumPy版
np_arange_9 = np.arange(9)
np_arange_9

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [43]:
# start, stopを指定
np_arange_29 = np.arange(2, 9)
np_arange_29

array([2, 3, 4, 5, 6, 7, 8])

In [44]:
# start, stop, stepを指定
np_arange_292 = np.arange(2, 9, 2)
np_arange_292

array([2, 4, 6, 8])

In [45]:
# 型指定もできます
np_arange_292_float = np.arange(2, 9, 2, dtype=float)
np_arange_292_float

array([ 2.,  4.,  6.,  8.])

In [46]:
# 浮動小数点数も使えます
np_arange_num7 = np.arange(2.5, 5.6, 0.5)
np_arange_num7

array([ 2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5])

In [47]:
# 範囲（start, stop）と個数（num）を指定
np_linspace_num7 = np.linspace(2.5, 5.5, 7)
np_linspace_num7

array([ 2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5])

In [48]:
# 3×3の単位行列（対角成分のみ1の行列）
np_eye_3 = np.eye(3)
np_eye_3

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [49]:
# 3×4のような非正方行列も可能
np_eye_34 = np.eye(3, 4)
np_eye_34

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.]])

In [50]:
# 対角行列（対角成分以外が0の行列）
np_diag = np.diag([10, 11, 12])
np_diag

array([[10,  0,  0],
       [ 0, 11,  0],
       [ 0,  0, 12]])

- Numpyで乱数を作ろう

In [52]:
# 1次元の一様乱数（10個の0以上1未満の数）
# 実行するたびに結果が変わります
rnd1 = np.random.rand(10)
rnd1

array([ 0.25377026,  0.23279283,  0.25299304,  0.95708433,  0.19120777,
        0.30330464,  0.54048874,  0.84888648,  0.29503384,  0.75261378])

In [53]:
# 2次元の乱数（2行5列）
rnd2 = np.random.rand(2, 5)
rnd2

array([[ 0.54961647,  0.34007538,  0.84653148,  0.90661112,  0.53755432],
       [ 0.15762652,  0.16598404,  0.34735275,  0.36497429,  0.91008099]])

In [54]:
# 3から5の一様乱数（10個）
rnd3 = np.random.uniform(3, 5, 10)
rnd3

array([ 3.74975108,  3.99891321,  4.44587514,  4.76340855,  3.47237345,
        4.7429808 ,  4.37452334,  3.21495832,  3.68987987,  4.13428438])

In [55]:
# 3から5の一様乱数（2行5列の2次元配列）
rnd4 = np.random.uniform(3, 5, (2, 5))
rnd4

array([[ 3.18052988,  4.33737882,  4.06393938,  3.28298117,  3.58243703],
       [ 4.48927306,  3.03701817,  4.48529496,  3.26388182,  3.33500848]])

- 整数乱数とランダム選択

In [57]:
rnd1 = np.random.randint(0, 3, 10)
rnd1

array([1, 0, 0, 1, 2, 1, 2, 1, 0, 1])

In [58]:
# [0, 3) の整数の乱数（多次元）
rnd2 = np.random.randint(0, 3, (2, 5))
rnd2

array([[1, 1, 2, 0, 1],
       [0, 1, 0, 1, 1]])

In [59]:
# リストからランダムに選択
targets = ['A', 'B', 'C']
rnd3 = np.random.choice(targets, 4)
rnd3

array(['B', 'B', 'C', 'A'], 
      dtype='<U1')

In [60]:
# リストからランダムに最大で1度だけ選択
rnd4 = np.random.choice(targets, 3, replace=False)
rnd4

array(['C', 'A', 'B'], 
      dtype='<U1')

In [61]:
# リストの順番をランダムに（元のリストはそのまま）
rnd5 = np.random.permutation(targets)
rnd5

array(['A', 'C', 'B'], 
      dtype='<U1')

In [62]:
# リストの順番をランダムに（元のリストを変更）
np.random.shuffle(targets)
targets

['C', 'A', 'B']

- 色々な分布の乱数

In [63]:
# 標準正規乱数（平均0、標準偏差1）
rnd1 = np.random.randn(10)
rnd1

array([ 0.30669908,  0.27224758,  0.15923026, -0.62172935,  0.7488153 ,
       -1.0083081 , -0.95020963,  2.18700965, -0.72356764,  0.52180176])

In [64]:
# 平均50、標準偏差10の正規乱数
rnd2 = np.random.normal(50, 10, 10)
rnd2

array([ 47.68499408,  60.30019966,  50.5606293 ,  55.18818785,
        45.57653302,  40.76797771,  42.88410385,  55.2644919 ,
        53.95476971,  53.77730652])

In [65]:
# 平均50、標準偏差10の正規乱数（多次元）
rnd3 = np.random.normal(50, 10, (2, 5))
rnd3

array([[ 47.67258871,  43.0013417 ,  50.59201213,  59.77363143,
         51.45400242],
       [ 33.00019741,  50.54013527,  58.4516854 ,  52.86495223,
         64.13456051]])

In [66]:
# α=1, β=2 のベータ乱数10個
rnd4 = np.random.beta(1, 2, 10)
rnd4

array([ 0.30519329,  0.07347813,  0.40621095,  0.17617605,  0.21588693,
        0.58008171,  0.51707477,  0.45987804,  0.0835046 ,  0.47206122])

In [67]:
# n=10, p=0.4 の二項乱数10個
rnd5 = np.random.binomial(10, 0.4, 10)
rnd5

array([2, 3, 3, 6, 2, 3, 7, 2, 5, 5])

In [68]:
# λ=0.8 のポアソン乱数10個
rnd6 = np.random.poisson(0.8, 10)
rnd6

array([1, 1, 2, 2, 1, 2, 1, 1, 1, 1])

In [69]:
# 平均が[0, 0]、共分散行列が[[1, 0.5], [0.5, 1]] の多次元正規乱数
rnd7 = np.random.multivariate_normal([0, 0], [[1, 0.5], [0.5, 1]])
rnd7

array([-0.16515045, -0.84165899])

- 乱数の再現性

In [70]:
# セルを何度実行しても結果は同じです
for _ in range(3):
    np.random.seed(0)
    print(np.random.randint(0, 10, 5))


[5 0 3 3 7]
[5 0 3 3 7]
[5 0 3 3 7]


In [71]:
# セルを実行するたびに、全体は変わりますが、3行は同じ行になります
state = np.random.get_state()
for _ in range(3):
    np.random.set_state(state)
    print(np.random.rand(5))

[ 0.4236548   0.64589411  0.43758721  0.891773    0.96366276]
[ 0.4236548   0.64589411  0.43758721  0.891773    0.96366276]
[ 0.4236548   0.64589411  0.43758721  0.891773    0.96366276]


In [72]:
# 多次元配列をファイルに保存
data = np.random.rand(5)
np.save('tmp.npy', data)
data

array([ 0.38344152,  0.79172504,  0.52889492,  0.56804456,  0.92559664])

In [73]:
# ファイルから多次元配列を取得
data = np.load('tmp.npy')
data  # 同じ多次元配列

array([ 0.38344152,  0.79172504,  0.52889492,  0.56804456,  0.92559664])