# 多次元配列の使い方を学ぼう　〜参照と代入〜

- インデックス参照

In [2]:
import numpy as np

# 2次元配列の作成
data = np.arange(6).reshape((2, -1))
data

array([[0, 1, 2],
       [3, 4, 5]])

In [3]:
# 1行目の配列
data0 = data[0]
data0

array([0, 1, 2])

In [4]:
# 2行目の配列
data1 = data[1]
data1

array([3, 4, 5])

In [5]:
# 1行目1列目の値
data_00 = data[0, 0]
data_00

0

In [6]:
# 1行目3列目の値
data_02 = data[0, 2]
data_02

2

In [7]:
# 行の配列にしてから列を取り出すのと同じ
data[0][2]

2

In [8]:
# 各次元ごとに、スライスを指定できる（「:」は全て）
data_0a = data[0, :]
data_0a

array([0, 1, 2])

In [9]:
# 列の取り出しが簡単にできる
# リストだと、[i[0] for i in data] のように書かないといけません
data_a0 = data[:, 0]
data_a0

array([0, 3])

In [10]:
# 部分行列も簡単に取り出せる
data_sub = data[:, :2]
data_sub

array([[0, 1],
       [3, 4]])

- 部分行列とコピー

In [12]:
import numpy as np

# 2次元配列の作成
data = np.arange(6).reshape((2, -1))
data

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
# 代入
data[0, 1] = 10
data

array([[ 0, 10,  2],
       [ 3,  4,  5]])

In [14]:
# 左上の2×2の部分行列
data_sub = data[:, :2]
data_sub

array([[ 0, 10],
       [ 3,  4]])

In [15]:
# 部分行列を変更
data_sub[0, 1] = 100
data_sub

array([[  0, 100],
       [  3,   4]])

In [16]:
# 元のデータも変更
data

array([[  0, 100,   2],
       [  3,   4,   5]])

In [17]:
# 別のデータにするには、copy
data_sub = data[:, :2].copy()
data_sub

array([[  0, 100],
       [  3,   4]])

In [19]:
# 部分行列を変更しても、元の行列は変わりません
data_sub[0, 1] = 1
data  # data[0, 1] は100のまま

array([[  0, 100,   2],
       [  3,   4,   5]])

多次元配列のスライスは、コピーではなく、ビューと呼ばれる。ビューは元データの参照を持っている。

- ファンシーインデックス参照

In [21]:
import numpy as np

# 2次元配列の作成
data = np.arange(12).reshape((4, -1))
data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
# 行をファンシーインデックス参照
data_13 = data[[1, 3]]
data_13

array([[ 3,  4,  5],
       [ 9, 10, 11]])

In [23]:
# 列をファンシーインデックス参照
data_02 = data[:, [0, 2]]
data_02

array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9, 11]])

In [24]:
# 指定した順番通りに取得
data_20 = data[:, [2,0]]
data_20

array([[ 2,  0],
       [ 5,  3],
       [ 8,  6],
       [11,  9]])

In [25]:
# インデックスはダブっても良い
# ３列目を２回取得
data_202 = data[:,[2, 0, 2]]
data_202

array([[ 2,  0,  2],
       [ 5,  3,  5],
       [ 8,  6,  8],
       [11,  9, 11]])

In [26]:
# 両方リストを指定すると、要素ごとになる
# [data[1, 0], data[3, 2]]と同じ
data[[1,3], [0, 2]]

array([ 3, 11])

In [29]:
# 元のデータとは別のデータになる
data_13 = data[[1,3]]
data[0,0] = 100
data_13

array([[ 3,  4,  5],
       [ 9, 10, 11]])

In [30]:
data

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10,  11]])

- ブールインデックス参照

In [31]:
import numpy as np

# 2次元配列の作成
data = np.arange(12).reshape((4, -1))
data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [32]:
# ファンシーインデックス参照
data[[1, 3]]

array([[ 3,  4,  5],
       [ 9, 10, 11]])

In [33]:
# ブールインデックス参照
data_ftft = data[[False, True, False, True]]
data_ftft

array([[ 3,  4,  5],
       [ 9, 10, 11]])

In [34]:
# ファンシーインデックス参照
data[:, [0, 2]]

array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9, 11]])

In [35]:
# ブールインデックス参照
data_tft = data[:, [True, False, True]]
data_tft

array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9, 11]])

- ブロードキャストとは？

In [36]:
import numpy as np

# 3次元配列
data3 = np.arange(8).reshape(2, 2, -1)
data3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [37]:
# 各次元のサイズ
data3.shape

(2, 2, 2)

In [38]:
# 各次元のサイズが同じものを足すと、
# 各要素ごとに足される
data33 = data3 + data3
data33

array([[[ 0,  2],
        [ 4,  6]],

       [[ 8, 10],
        [12, 14]]])

In [39]:
# 2次元配列
data2 = np.array([[10, 11], [12, 13]])
data2

array([[10, 11],
       [12, 13]])

In [40]:
# 異なる次元数の足し算
data23 = data2 + data3
data23

array([[[10, 12],
        [14, 16]],

       [[14, 16],
        [18, 20]]])

In [41]:
# data2 を複製して、2×2×2の data22 を作成
data22 = np.array([data2, data2])
data22

array([[[10, 11],
        [12, 13]],

       [[10, 11],
        [12, 13]]])

In [42]:
# data2 + data3 と同じ結果
data223 = data22 + data3
data223

array([[[10, 12],
        [14, 16]],

       [[14, 16],
        [18, 20]]])

- 小さい次元のブロードキャスト

In [43]:
import numpy as np

# 3次元配列
data3 = np.arange(8).reshape(2, 2, -1)
data3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [44]:
#１次元配列
data1 = np.array([10, 11])
data1

array([10, 11])

In [45]:
# 異なる次元数の足し算
data13 = data1 + data3
data13

array([[[10, 12],
        [12, 14]],

       [[14, 16],
        [16, 18]]])

In [46]:
# data1を複製して、2*2*2のdata11のdata11を作成
data11 = np.array([[data1, data1], [data1, data1]])
data113 = data11 + data3
data113

array([[[10, 12],
        [12, 14]],

       [[14, 16],
        [16, 18]]])

In [47]:
# 0次元のスカラーとの足し算
data0 = 10
data03 = data0 + data3
data03

array([[[10, 11],
        [12, 13]],

       [[14, 15],
        [16, 17]]])

In [48]:
# data0を複製して、data3と同じ2*2*2のdata00を作成
data00 = np.full_like(data3, data0)
data00

array([[[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]]])

In [49]:
# data0 + data3の結果と同じ
data003 = data00 + data3
data003

array([[[10, 11],
        [12, 13]],

       [[14, 15],
        [16, 17]]])

- ブロードキャストの考え方

In [51]:
import numpy as np

# 要素が0の3×2×4の3次元配列
data0 = np.zeros((3, 2, 4))
data0

array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

In [52]:
# 1次元配列
data1 = np.arange(4)
data1

array([0, 1, 2, 3])

In [53]:
data01 = data0 + data1
data01

array([[[ 0.,  1.,  2.,  3.],
        [ 0.,  1.,  2.,  3.]],

       [[ 0.,  1.,  2.,  3.],
        [ 0.,  1.,  2.,  3.]],

       [[ 0.,  1.,  2.,  3.],
        [ 0.,  1.,  2.,  3.]]])

In [54]:
# ２次元配列
data2 = np.arange(8).reshape(2, 4)
data2

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [55]:
#2次元配列と足し算
data02 = data0 + data2
data02

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]]])

In [57]:
#3次元配列
data3 = np.arange(12).reshape(3,1,4)
data3

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [58]:
#3次元配列と足し算
data03 = data0 + data3
data03

array([[[  0.,   1.,   2.,   3.],
        [  0.,   1.,   2.,   3.]],

       [[  4.,   5.,   6.,   7.],
        [  4.,   5.,   6.,   7.]],

       [[  8.,   9.,  10.,  11.],
        [  8.,   9.,  10.,  11.]]])

ブロードキャストの考え方

変数data1と、次元数が同じか小さい変数data2を考えます。

data1の次元数はn+k、data2の次元数はnとします（k >= 0）。

shape1をdata1のshape = (m[1, 1], m[1, 2], …, m[1, n+k])とします。

shape2をdata2のshape = (m[2, 1+k], m[2, 2+k], …, m[2, n+k])とします。

shape2の頭にk個の1を追加してサイズがnになるようにします。

shape2 = (m[2, 1], m[2, 2], …, m[2, n+k])（ただし、m[2, 1] = m[2, 1] = … = m[2, k] = 1）とします。

data1.shape == (3, 2, 4)の時、どのようになるか図で見てみましょう。

data2.shapeが (4, ), (2, 4), (3, 1, 4)の3ケースを表示します。



ブロードキャストの成立条件

ブロードキャストは、サイズが同じなるように伸ばします。

i = 1, 2, ..., n+kとなる全てのiに対し、m[1, i] == m[2, i] または m[1, i], m[2, i]のどちらかが1のとき、ブロードキャストできます。

逆にいうと、m[1, i] > 1 and m[2, i] > 1 and m[1, i] != m[2, i]となるiがあると、ブロードキャストできません。

先程の図で、この条件を満たしていることを確認してみましょう。

ブロードキャストでは、各次元ごとにサイズが同じになるように、足りなければ複製します。

- ブロードキャストをもっと学ぼう（次元が異なる配列の代入や比較）

In [59]:
import numpy as np

# 要素が0の3×2×4の3次元配列
data0 = np.zeros((3, 2, 4))
data0

array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

In [60]:
# 各次元の多次元配列（全て先頭だけ0）
data1 = np.arange(4)
data2 = np.arange(8).reshape(2, 4)
data3 = np.arange(12).reshape(3, 1, 4)
data1

array([0, 1, 2, 3])

In [61]:
data2

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [62]:
data3

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [63]:
# ブロードキャストして比較
data01 = data0 == data1
data01

array([[[ True, False, False, False],
        [ True, False, False, False]],

       [[ True, False, False, False],
        [ True, False, False, False]],

       [[ True, False, False, False],
        [ True, False, False, False]]], dtype=bool)

In [64]:
# ブロードキャストして比較
data02 = data0 == data2
data02

array([[[ True, False, False, False],
        [False, False, False, False]],

       [[ True, False, False, False],
        [False, False, False, False]],

       [[ True, False, False, False],
        [False, False, False, False]]], dtype=bool)

In [65]:
# ブロードキャストして比較
data03 = data0 == data3
data03

array([[[ True, False, False, False],
        [ True, False, False, False]],

       [[False, False, False, False],
        [False, False, False, False]],

       [[False, False, False, False],
        [False, False, False, False]]], dtype=bool)

- ブロードキャストして代入

In [66]:
import numpy as np

# 各次元の多次元配列（全て先頭だけ0）
data1 = np.arange(4)
data2a = np.arange(2).reshape(2, 1)
data2b = np.arange(8).reshape(2, 4)
data3 = np.arange(12).reshape(3, 1, 4)
data1

array([0, 1, 2, 3])

In [67]:
data2a

array([[0],
       [1]])

In [68]:
data2b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [69]:
data3

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [73]:
# ブロードキャストして代入
data01a = np.zeros((3, 2, 4))
data01a

array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

In [72]:
data01a[:] = data1
data01a

array([[[ 0.,  1.,  2.,  3.],
        [ 0.,  1.,  2.,  3.]],

       [[ 0.,  1.,  2.,  3.],
        [ 0.,  1.,  2.,  3.]],

       [[ 0.,  1.,  2.,  3.],
        [ 0.,  1.,  2.,  3.]]])

In [75]:
# 「+=」は「[:]」がなくても使える
data01b = np.zeros((3, 2, 4))
data01b

array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

In [76]:
data01b += data1
data01b

array([[[ 0.,  1.,  2.,  3.],
        [ 0.,  1.,  2.,  3.]],

       [[ 0.,  1.,  2.,  3.],
        [ 0.,  1.,  2.,  3.]],

       [[ 0.,  1.,  2.,  3.],
        [ 0.,  1.,  2.,  3.]]])

In [78]:
# ブロードキャストして代入
data02a = np.zeros((3, 2, 4))
data02a

array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

In [79]:
data02a[:] = data2a
data02a

array([[[ 0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.]],

       [[ 0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.]],

       [[ 0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.]]])

In [80]:
# ブロードキャストして代入
data02b = np.zeros((3, 2, 4))
data02b[:] = data2b
data02b

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]]])

In [81]:
# ブロードキャストして代入
data03 = np.zeros((3, 2, 4))
data03[:] = data3
data03

array([[[  0.,   1.,   2.,   3.],
        [  0.,   1.,   2.,   3.]],

       [[  4.,   5.,   6.,   7.],
        [  4.,   5.,   6.,   7.]],

       [[  8.,   9.,  10.,  11.],
        [  8.,   9.,  10.,  11.]]])

In [82]:
# 代入とアドレス
data03 = np.zeros((3, 2, 4))
print(id(data03))  # data3のアドレス
data03 += data3
print(id(data03))  # 「+=」でアドレスは変わりません
data03[:] = data3
print(id(data03))  # 「=」でアドレスは変わりません
data03 = data3
print(id(data03))  # 「=」でアドレスは変わります

4571127280
4571127280
4571127280
4571148976


- 比較と代入

In [83]:
import numpy as np

# 3×4の2次元配列を元に変更を加えます
data_org = np.arange(12).reshape(3, -1)
data_org

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
# 奇数を -1 倍に
data1 = data_org.copy()  # コピーして変更
data1[data1 % 2 == 1] *= -1
data1

array([[  0,  -1,   2,  -3],
       [  4,  -5,   6,  -7],
       [  8,  -9,  10, -11]])

In [85]:
# 偶数に +1
data2 = data_org.copy()
data2[data2 % 2 == 0] += 1
data2

array([[ 1,  1,  3,  3],
       [ 5,  5,  7,  7],
       [ 9,  9, 11, 11]])

In [86]:
# 6未満を -1 に
data3 = data_org.copy()
data3[data3 < 6] = -1
data3

array([[-1, -1, -1, -1],
       [-1, -1,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
# AND は &（アンパサンド）でできます
data4 = data_org.copy()
data4[(4 <= data4) & (data4 < 8)] = -1
data4

array([[ 0,  1,  2,  3],
       [-1, -1, -1, -1],
       [ 8,  9, 10, 11]])

In [88]:
# OR は |（パイプ）でできます
data5 = data_org.copy()
data5[(data5 < 4) | (8 <= data5)] = -1
data5

array([[-1, -1, -1, -1],
       [ 4,  5,  6,  7],
       [-1, -1, -1, -1]])

In [89]:
# NOT は ~（チルダ）で
data6 = data_org.copy()
data6[~(data6 < 6)] = -1
data6

array([[ 0,  1,  2,  3],
       [ 4,  5, -1, -1],
       [-1, -1, -1, -1]])

- セル・オートマトン

In [91]:
import numpy as np

In [92]:
data = np.zeros(33, dtype=int)
data[16] = 1
data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

ルール90

0または1を取る1次元配列を用います（初期値は1つだけ1とします）。

次のステップでは、自分の左右の要素の値の和を2で割った余りとします。

In [93]:
# chooseの例
np.array([1,0,2]).choose(['A', 'B', 'C'])

array(['B', 'A', 'C'], 
      dtype='<U1')

In [94]:
# 文字列をそのまま渡してもおっけー
np.array([1, 0, 2]).choose('ABC')

array(['B', 'A', 'C'], 
      dtype='<U1')

In [95]:
# 要素が1の時に「#」に
data.choose('.#')

array(['.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.',
       '.', '.', '.', '#', '.', '.', '.', '.', '.', '.', '.', '.', '.',
       '.', '.', '.', '.', '.', '.', '.'], 
      dtype='<U1')

In [96]:
# 文字のリストを連結
''.join(data.choose('.#'))

'................#................'

In [97]:
data[1:-1] = (data[:-2] + data[2:]) %2
print(''.join(data.choose('.#')))

...............#.#...............


In [98]:
data[1:-1] = (data[:-2] + data[2:]) % 2
print(''.join(data.choose('.#')))

..............#...#..............


In [99]:
data[1:-1] = (data[:-2] + data[2:]) % 2
print(''.join(data.choose('.#')))

.............#.#.#.#.............


In [100]:
data = np.zeros(33, dtype=int)  # 初期化
data[16] = 1  # 中央を1に
for _ in range(16):
    print(''.join(data[1:-1].choose('.#')))  # 描画
    data[1:-1] = (data[:-2] + data[2:]) % 2  # 更新

...............#...............
..............#.#..............
.............#...#.............
............#.#.#.#............
...........#.......#...........
..........#.#.....#.#..........
.........#...#...#...#.........
........#.#.#.#.#.#.#.#........
.......#...............#.......
......#.#.............#.#......
.....#...#...........#...#.....
....#.#.#.#.........#.#.#.#....
...#.......#.......#.......#...
..#.#.....#.#.....#.#.....#.#..
.#...#...#...#...#...#...#...#.
#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#
